." Copyright (c) 2004, 2011, Oracle and/or its affiliates. All rights reserved.
." DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
."
." This code is free software; you can redistribute it and/or modify it
." under the terms of the GNU General Public License version 2 only, as
." published by the Free Software Foundation.
."
." This code is distributed in the hope that it will be useful, but WITHOUT
." ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
." FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
." version 2 for more details (a copy is included in the LICENSE file that
." accompanied this code).
."
." You should have received a copy of the GNU General Public License version
." 2 along with this work; if not, write to the Free Software Foundation,
." Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
."
." Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
." or visit www.oracle.com if you need additional information or have any
." questions.
."
.TH jps 1 "21 Mar 2012"

.LP
.SH "名前"
jps \- Java仮想マシン・プロセス・ステータス・ツール
.LP
.RS 3
.TP 2
o
形式 
.TP 2
o
パラメータ 
.TP 2
o
説明 
.TP 2
o
オプション 
.TP 2
o
ホスト識別子 
.TP 2
o
出力形式 
.TP 2
o
例 
.TP 2
o
関連項目 
.RE

.LP
.SH "形式"
.LP
.nf
\f3
.fl
\fP\f3jps\fP [ \f2options\fP ] [ \f2hostid\fP ]
.br

.fl
.fi

.LP
.SH "パラメータ"
.LP
.RS 3
.TP 3
options 
コマンドライン・オプション。 
.TP 3
hostid 
プロセス・レポートを生成するホストのホスト識別子。\f2hostid\fPには、通信プロトコル、ポート番号、実装に固有な他のデータを指定したオプション・コンポーネントを含めることができます。 
.RE

.LP
.SH "説明"
.LP
.LP
\f3jps\fPツールは、ターゲット・システム上で計測されたHotSpot Java仮想マシン(JVM)を一覧表示します。このツールで表示できるレポート情報は、アクセス権を持ったJVMに関するものに限定されます。
.LP
.LP
\f2hostid\fPを指定せずに\f3jps\fPを実行した場合、ローカル・ホストで計測されたJVMが検索されます。\f2hostid\fPを指定して起動した場合、指定されたプロトコルとポートを使用して、指定されたホスト上のJVMを検索します。\f3jstatd\fPプロセスがターゲット・ホスト上で実行されていると想定されます。
.LP
.LP
\f3jps\fPコマンドは、ターゲット・システムで計測された各JVMについて、ローカルVM識別子、つまり\f2lvmid\fPをレポートします。\f3lvmid\fPは、一般的にはJVMプロセスに対するオペレーティング・システムのプロセス識別子ですが、必ずしもそうであるとは限りません。オプションを指定しない場合、\f3jps\fPによって、各Javaアプリケーションの\f2lvmid\fPが一覧表示され、それぞれにアプリケーションのクラス名またはJARファイル名が簡単な形式で示されます。この簡単な形式のクラス名とJARファイル名では、クラスのパッケージ情報またはJARファイル・パス情報が省略されています。
.LP
.LP
\f3jps\fPコマンドは、\f3Java\fP起動ツールを使用して\f2main\fPメソッドに渡されるクラス名と引数を検索します。独自の起動ツールを使用してターゲットJVMを起動した場合は、\f2main\fPメソッドに渡されるクラス名(またはJARファイル名)と引数は利用できません。この場合、\f3jps\fPコマンドは、mainメソッドに渡されるクラス名(またはJARファイル名)と引数に対して、文字列\f2Unknown\fPを出力します。
.LP
.LP
\f3jps\fPコマンドで生成されるJVMのリストは、このコマンドを実行するプリンシパルに与えられたアクセス権に基づき、制限される場合があります。このコマンドは、オペレーティング・システム独自のアクセス制御機構による決定に基づいて、プリンシパルにアクセス権が与えられているJVMのみを一覧表示します。
.LP
.LP
\f3注意:\fP このユーティリティはサポート対象外であり、将来のJDKのバージョンでは利用できなくなる可能性があります。現在、Windows 98およびWindows MEプラットフォームでは使用できません。
.LP
.SH "オプション"
.LP
.LP
\f3jps\fPコマンドでは、コマンドの出力を変更するオプションが多数サポートされています。将来、これらのオプションは、変更または廃止される可能性があります。
.LP
.RS 3
.TP 3
\-q 
クラス名、JARファイル名、および\f2main\fPメソッドに渡された引数の出力を抑制し、ローカルVM識別子の一覧のみを生成します。 
.TP 3
\-m 
mainメソッドに渡される引数を出力します。この出力は、組み込まれているJVMに対してnullになることもあります。  
.TP 3
\-l 
アプリケーションのメイン・クラスのフル・パッケージ名、またはアプリケーションのJARファイルへのフルパス名を出力します。 
.TP 3
\-v 
JVMに渡される引数を出力します。 
.TP 3
\-V 
フラグ・ファイル(.hotspotrcファイルまたは\-XX:Flags=<\f2filename\fP>の引数で指定されたファイル)を通じてJVMに渡される引数を出力します。 
.TP 3
\-Joption 
\f3jps\fPが呼び出す\f3java\fP起動ツールに、\f2option\fPを渡します。たとえば、\f3\-J\-Xms48m\fPと指定すると、スタートアップ・メモリーは48Mバイトに設定されます。\f3\-J\fPを使用して、Javaで記述されたアプリケーションを実行する背後のVMにオプションを渡すことは、よく行われています。 
.RE

.LP
.SS 
ホスト識別子
.LP
.LP
ホスト識別子、つまり\f2hostid\fPは、ターゲット・システムを示す文字列です。\f2hostid\fP文字列の構文の大部分は、URIの構文に対応しています。
.LP
.nf
\f3
.fl
[\fP\f4protocol\fP\f3:][[//]\fP\f4hostname\fP\f3][:\fP\f4port\fP\f3][/\fP\f4servername\fP\f3]\fP
.br
\f3
.fl
\fP
.fi

.LP
.RS 3
.TP 3
protocol 
通信プロトコルです。\f2protocol\fPが省略され、\f2hostname\fPが指定されていない場合、デフォルトのプロトコルが、プラットフォーム固有の最適化されたローカル・プロトコルになります。\f2protocol\fPが省略され、\f2hostname\fPが指定されている場合は、デフォルト・プロトコルは\f3rmi\fPになります。 
.TP 3
hostname 
ターゲット・ホストを示すホスト名またはIPアドレスです。\f2hostname\fPが省略されている場合は、ターゲット・ホストはローカル・ホストになります。 
.TP 3
port 
リモート・サーバーと通信するためのデフォルト・ポートです。\f2hostname\fPが省略されているか、最適化されたローカル・プロトコルが\f2protocol\fPに指定されている場合、\f2port\fPは無視されます。それ以外の場合、\f2port\fPパラメータの扱いは、実装によって異なります。デフォルトの\f3rmi\fPプロトコルの場合、\f2port\fPは、リモート・ホスト上のrmiregistryのポート番号を示します。\f2port\fPが省略され、\f2protocol\fPで\f3rmi\fPが指定されている場合、デフォルトのrmiregistryポート(1099)が使用されます。 
.TP 3
servername 
このパラメータの扱いは、実装によって異なります。最適化されたローカル・プロトコルの場合、このフィールドは無視されます。\f3rmi\fPプロトコルの場合、このパラメータは、リモート・ホスト上のRMIリモート・オブジェクトの名前を示す文字列になります。jstatd(1)コマンドの\f3\-n\fPオプションを参照してください。 
.RE

.LP
.SH "出力形式"
.LP
.LP
\f3jps\fPコマンドの出力は、次のパターンに従います。
.LP
.nf
\f3
.fl
\fP\f4lvmid\fP\f3 [ [ \fP\f4classname\fP\f3 | \fP\f4JARfilename\fP\f3 | "Unknown"] [ \fP\f4arg\fP\f3* ] [ \fP\f4jvmarg\fP\f3* ] ]\fP
.br
\f3
.fl
\fP
.fi

.LP
.LP
すべての出力トークンは空白で区切ります。\f2arg\fPの中で空白を使用すると、実際の定位置パラメータに引数をマッピングしようとするときに、あいまいになります。
.br
.br
\f3注意\fP: 将来のリリースでこの形式は変更される可能性があるため、\f3jps\fPの出力を解析するスクリプトは作成しないことをお薦めします。\f3jps\fP出力を解析するスクリプトを作成すると、このツールの将来のリリースで、作成したスクリプトの変更が必要になる可能性があります。
.br

.LP
.SH "例"
.LP
.LP
この項では、\f3jps\fPコマンドの例を示します。
.LP
.LP
ローカル・ホスト上で計測されたJVMを一覧表示する場合:
.LP
.nf
\f3
.fl
\fP\f3jps\fP
.br

.fl
18027 Java2Demo.JAR
.br

.fl
18032 jps
.br

.fl
18005 jstat
.br

.fl
.fi

.LP
.LP
リモート・ホスト上で計測されたJVMを一覧表示する場合:
.LP
.LP
この例では、\f3jstat\fPサーバーと、その内部RMIレジストリまたは別の外部\f3rmiregistry\fPプロセスのいずれかが、リモート・ホストのデフォルト・ポート(ポート1099)で実行されていると想定しています。また、ローカル・ホストが、リモート・ホストへの有効なアクセス権を持っていることも想定しています。この例には、\f2\-l\fPオプションも含まれ、クラス名またはJARファイル名を詳細な形式で出力します。
.LP
.nf
\f3
.fl
\fP\f3jps \-l remote.domain\fP
.br

.fl
3002 /opt/jdk1.7.0/demo/jfc/Java2D/Java2Demo.JAR
.br

.fl
2857 sun.tools.jstatd.jstatd
.br

.fl
.fi

.LP
.LP
RMIレジストリにデフォルトではないポートを使用して、リモート・ホスト上で計測されたJVMを一覧表示する場合:
.LP
.LP
この例では、内部RMIレジストリがポート2002にバインドされた\f3jstatd\fPサーバーが、リモート・ホスト上で実行されていると想定しています。また、\f2\-m\fPオプションを使用して、一覧表示されたそれぞれのJavaアプリケーションの\f2main\fPメソッドに渡される引数を組み込んでいます。
.LP
.nf
\f3
.fl
\fP\f3jps \-m remote.domain:2002\fP
.br

.fl
3002 /opt/jdk1.7.0/demo/jfc/Java2D/Java2Demo.JAR
.br

.fl
3102 sun.tools.jstatd.jstatd \-p 2002
.fl
.fi

.LP
.SH "関連項目"
.LP
.RS 3
.TP 2
o
java(1) \- Javaアプリケーション起動ツール 
.TP 2
o
jstat(1) \- Java仮想マシン統計データ監視ツール 
.TP 2
o
jstatd(1) \- jstatデーモン 
.TP 2
o
rmiregistry(1) \- Javaリモート・オブジェクト・レジストリ 
.RE

.LP
 
